// <auto-generated />
namespace TurkishHomeApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createunitslist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createunitslist));
        
        string IMigrationMetadata.Id
        {
            get { return "202105171211205_create-units-list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
